### ISSUE TITLE
It ran for a very long time with no results, showing gpu is occupied

### ISSUE THREAD

**Issue by Enderfga** [mindspore-lab/minddiffusion#23]
I am using mindspore 1.9 , the gpu is a 24g 3090 and both models ran for a long time without results and finally showed the following reported error.

RuntimeError: For 'BatchMatMul', encountered an exception: cuBLAS Error: cublasGemmStridedBatchedEx failed. Possible reasons: the GPU is occupied by other processes. | Error Number: 15 CUBLAS_STATUS_NOT_SUPPORTED: The functionality requested is not supported.

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/plugin/device/gpu/kernel/math/matmul_gpu_kernel.cc:155 LaunchKernel
mindspore/ccsrc/plugin/device/gpu/kernel/math/matmul_gpu_kernel.cc:152 LaunchKernel
 when invoke cublas cublasGemmStridedBatchedEx

**Comment by Enderfga** [comment]
Is there no GPU support at all at the moment?

**Comment by congw729** [comment]
Sorry, our models, including Taichu-GLIDE and Wukong-Huahua, are only supported in Ascend for now, not GPU.

**Comment by Enderfga** [comment]
Okay, I get it. Thanks for the replies.
