### ISSUE TITLE
执行 bash scripts/run_db_train.sh报错

### ISSUE THREAD

**Issue by amazingUing** [mindspore-lab/minddiffusion#61]
环境：
Ascend910  eulerosv2r8.aarch64
mindspore-ascend       1.9.0

任务二：个性化文生图任务
执行 bash scripts/run_db_train.sh报错

报错信息：
process id: 21111
Namespace(betas=[0.9, 0.98], callback_size=1, class_word='猫', data_path='/secHome/FFHQ', decay_steps=0, dropout=0.1, end_learning_rate=1e-07, epochs=5, filter_small_size=True, gradient_accumulation_steps=1, image_filter_size=256, image_size=512, init_loss_scale=65536, loss_scale_factor=2, model_config='/home/data/wukong/minddiffusion/vision/wukong-huahua/configs/v1-train-db-chinese.yaml', optim='adamw', output_path='output/α猫', patch_size=32, pretrained_model_file='wukong-huahua-ms.ckpt', pretrained_model_path='models', random_crop=False, reg_data_path='dataset/reg_cat', save_checkpoint_steps=1000, scale_window=1000, seed=3407, start_learning_rate=1e-06, token='α', train_batch_size=1, train_config='/home/data/wukong/minddiffusion/vision/wukong-huahua/configs/train_db_config.json', train_data_path='dataset/train_cat', train_data_repeats=100, use_parallel=False, warmup_steps=100, weight_decay=0.01)
random seed:  3407
Total training images: 5
Total regularization images: 200
The training data is repeated 100 times, and the total number is 505
rank id 0, sample num is 505
LatentDiffusionDB: Running in eps-prediction mode
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
start loading pretrained_ckpt models/wukong-huahua-ms.ckpt
param not load: ['first_stage_model.encoder.down.3.downsample.conv.weight', 'first_stage_model.encoder.down.3.downsample.conv.bias', 'first_stage_model.decoder.up.0.upsample.conv.weight', 'first_stage_model.decoder.up.0.upsample.conv.bias']
end loading ckpt
start_training...
Traceback (most recent call last):
  File "run_db_train.py", line 255, in <module>
    main(args)
  File "run_db_train.py", line 211, in main
    model.train(opts.epochs, dataset, callbacks=callback, dataset_sink_mode=False)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mindspore/train/model.py", line 1050, in train
    initial_epoch=initial_epoch)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mindspore/train/model.py", line 98, in wrapper
    func(self, *args, **kwargs)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mindspore/train/model.py", line 617, in _train
    self._train_process(epoch, train_dataset, list_callback, cb_params, initial_epoch, valid_infos)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mindspore/train/model.py", line 908, in _train_process
    outputs = self._train_network(*next_element)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mindspore/nn/cell.py", line 596, in __call__
    out = self.compile_and_run(*args)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mindspore/nn/cell.py", line 985, in compile_and_run
    self.compile(*inputs)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mindspore/nn/cell.py", line 957, in compile
    jit_config_dict=self._jit_config_dict)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mindspore/common/api.py", line 1131, in compile
    result = self._graph_executor.compile(obj, args_list, phase, self._use_vm_mode())
RuntimeError: Got unexpected keyword argument: c_concat

----------------------------------------------------
- The Traceback of Net Construct Code:
----------------------------------------------------
The function call stack (See file '/home/data/wukong/minddiffusion/vision/wukong-huahua/rank_0/om/analyze_fail.dat' for more details. Get instructions about `analyze_fail.dat` at https://www.mindspore.cn/search?inputValue=analyze_fail.dat):
# 0 In file /usr/local/python3.7.5/lib/python3.7/site-packages/mindspore/nn/wrap/loss_scale.py:336
        loss = self.network(*inputs)
               ^
# 1 In file /home/data/wukong/minddiffusion/vision/wukong-huahua/ldm/models/diffusion/ddpm.py:481
        loss_train = self.shared_step(train_x, train_c)
                     ^
# 2 In file /home/data/wukong/minddiffusion/vision/wukong-huahua/ldm/models/diffusion/ddpm.py:477
        loss = self.p_losses(x, c, t)
               ^
# 3 In file /home/data/wukong/minddiffusion/vision/wukong-huahua/ldm/models/diffusion/ddpm.py:500
        loss_simple = self.get_loss(model_output, target, mean=False).mean([1, 2, 3])
                                    ^

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/core/ir/func_graph_extends.cc:139 GenerateKwParams

**Comment by LoomisChen** [comment]
已有pr解决
