### ISSUE TITLE
infer报错

### ISSUE THREAD

**Issue by weinan-c** [mindspore-lab/minddiffusion#64]
If this is your first time, please read our contributor guidelines:
https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md

minddiffusion/vision/stablediffusionv2
按照readme操作安装requirement.txt，bash script/infer.sh
报错
![image](https://github.com/mindspore-lab/minddiffusion/assets/51950918/21bd3a58-a515-4887-b976-1beae39e2fa8)
![image](https://github.com/mindspore-lab/minddiffusion/assets/51950918/45a15ed3-6c7f-4c41-9334-01015f5f0aff)

芯片版本
![image](https://github.com/mindspore-lab/minddiffusion/assets/51950918/46cce2a4-cf0f-48bc-8af1-8a39f6f6e86d)

- **Software Environment / 软件环境 (Mandatory / 必填)**:
![image](https://github.com/mindspore-lab/minddiffusion/assets/51950918/0c678596-8996-4320-9c0f-6210a9be3f67)
![image](https://github.com/mindspore-lab/minddiffusion/assets/51950918/4b628a53-f48f-4e4a-a5d7-e04b08e49a7b)
-- OS platform and distribution (e.g., Linux Ubuntu 18.04):
![image](https://github.com/mindspore-lab/minddiffusion/assets/51950918/7468448d-dae2-4a88-8e04-de6f64219abd)
![image](https://github.com/mindspore-lab/minddiffusion/assets/51950918/f0d7aeaa-112e-41e8-b27d-96dac371ee57)

![image](https://github.com/mindspore-lab/minddiffusion/assets/51950918/3fd4defe-995d-4d71-b34a-acc6fb1af769)

cd minddiffusion/vision/stablediffusionv2
bash script/infer.sh

**Expected behavior / 预期结果 (Mandatory / 必填)**
生成图片

**Screenshots/ 日志 / 截图 (Mandatory / 必填)**
![image](https://github.com/mindspore-lab/minddiffusion/assets/51950918/21bd3a58-a515-4887-b976-1beae39e2fa8)
![image](https://github.com/mindspore-lab/minddiffusion/assets/51950918/45a15ed3-6c7f-4c41-9334-01015f5f0aff)

**Comment by LoomisChen** [comment]
请参考文档说明安装mindspore版本
