### ISSUE TITLE
stable diffusionv2 训练有适配计划吗？

### ISSUE THREAD

**Issue by LeeLear** [mindspore-lab/minddiffusion#66]
If this is your first time, please read our contributor guidelines: https://gitee.com/mindspore/mindspore/blob/master/CONTRIBUTING.md

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by congw729** [comment]
Hi, pls check the updates of this repo https://github.com/mindspore-lab/mindone/tree/master/examples/stable_diffusion_v2
