### ISSUE TITLE
wukong-huahua lora微调from tk.graph import freeze_delta 中tk是什么工具包，仓库里没有看到，也不知道在哪里安装

### ISSUE THREAD

**Issue by drizzlezyk** [mindspore-lab/minddiffusion#70]
If this is your first time, please read our contributor guidelines:
https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md

**Describe the bug/ 问题描述 (Mandatory / 必填)**
wukong-huahua lora微调from tk.graph import freeze_delta 中tk是什么工具包，仓库里没有看到，也不知道在哪里安装

- **Hardware Environment(`Ascend`/`GPU`/`CPU`)  / 硬件环境**:
> Please delete the backend not involved / 请删除不涉及的后端:
> /device ascend/GPU/CPU/kirin/等其他芯片: Ascend910

- **Software Environment / 软件环境 (Mandatory / 必填)**:
-- MindSpore version (e.g., 1.7.0.Bxxx) : 1.9
-- Python version (e.g., Python 3.7.5) :3.9
-- OS platform and distribution (e.g., Linux Ubuntu 16.04):16.04
-- GCC/Compiler version (if compiled from source):

- **Excute Mode / 执行模式 (Mandatory / 必填)(`PyNative`/`Graph`)**:
> Please delete the mode not involved / 请删除不涉及的模式:
> /mode pynative
> /mode graph

**To Reproduce / 重现步骤 (Mandatory / 必填)**
1. Go to 'wukong-huahua'

**Expected behavior / 预期结果 (Mandatory / 必填)**

**Screenshots/ 日志 / 截图 (Mandatory / 必填)**
![image](https://github.com/mindspore-lab/minddiffusion/assets/43944770/a5656116-4103-4117-98e5-b0927d3d206e)

**Additional context / 备注 (Optional / 选填)**

**Comment by amazingUing** [comment]
安装微调包

git clone https://github.com/mindspore-lab/mindpet.git
cd mindpe
python3 set_up.py bdist_wheel
pip install dist/mindpet-1.0.0-py3-none-any.whl

**Comment by amazingUing** [comment]
任务四：适配LoRA微调算法+通用文生图任务
LoRA微调算法说明
目前已基于通用文生图任务，适配LoRA低参微调算法，仅需微调0.07%的参数量，就可在保持精度的情况下，大幅降低计算和存储成本。

LoRA微调算法具体接口说明请参考[《MindPet - delta 轻量化微调算法用户文档》](https://github.com/mindspore-lab/mindpet/blob/master/doc/TK_DeltaAlgorithm_README.md)第一章节。

MindPet中提供了LoRA/Prefix/Adapter/LowRankAdapter/Bitfit/RDrop等六种高效的微调算法，可自行选择适配悟空画画模型。

准备checkpoint
下载Wukong-Huahua预训练参数 [wukong-huahua-inpaint-ms.ckpt](https://download.mindspore.cn/toolkits/minddiffusion/wukong-huahua/wukong-huahua-inpaint-ms.ckpt) 至 wukong-huahua/models/ 目录。


使用的是wukong-huahua-ms.ckpt模型，不是wukong-huahua-inpaint-ms.ckp
